### ISSUE TITLE
when starting v4 initial notification are AM/PM

### ISSUE THREAD

**Issue by dkmur** [KartulUdus/PoracleJS#111]
## Expected Behavior
all notifications should be 24h format, for me at least :P

## Current Behavior
at v4 start/restart initial notifications are en 12 hour format afterwards notifications are send in 24h format

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. npm 5.6.0, nodejs v7.4.0):
* Operating System

**Comment by JimBim89** [comment]
Can confirm, using latest commit from Feb 21, 2020.

**Comment by jfberry** [comment]
Closing as part of general tidy up, please re-open if still an issue
