### ISSUE TITLE
Feature: A Map with overlays of distance-radius circles

### ISSUE THREAD

**Issue by quiddity-wp** [KartulUdus/PoracleJS#132]
## Context
This will 
* help people to set perfect distances for themselves, and 
* better understand how the distance-feature works.

## Desired Behavior
As a user, I want a Map that shows my centered Poracle `!location`, with overlay circles showing the distance-radius for 0.5/1/2/3/4/5 kilometres away. 

## Possible Solution
Perhaps there's some way to make GoogleMaps automatically show an overlay like this, as output from the `!tracked` command?

Or, maybe someone can invent a `!radius` command? :-D

Example:  I've found this site, which kinda works, but it doesn't adjust the placement of the circles if you type in a new address directly (awkward drag-and-drop x5, or you have to recreate the circles yourself from a fresh map). 
E.g. 0.5km/1km/2km circles. https://www.mapdevelopers.com/draw-circle-tool.php?circles=%5B%5B1000%2C43.3199051%2C6.2897851%2C%22%23AAAAAA%22%2C%22%23000000%22%2C0%5D%2C%5B500%2C43.3199051%2C6.2897851%2C%22%23AAAAAA%22%2C%22%23000000%22%2C0%5D%2C%5B2000%2C43.3199051%2C6.2897851%2C%22%23AAAAAA%22%2C%22%23000000%22%2C0%5D%5D

## Future documentation notes
:world_map: :red_circle: :diamond_shape_with_a_dot_inside: Maps radius circles! -- "How far away is that park?" -- Wonder no more! 0.5km/1km/2km circles! Type `!radius 123 common road, town` to see a visualization.

**Comment by jfberry** [comment]
That site works quite well, you can use the long/lat poracle gives you from !tracked and add the circles quite quickly

**Comment by quiddity-wp** [comment]
Yeah, that existing site is ok for semi-technical folks who don't mind fiddling for 5 minutes, but it could be way easier for others!

**Comment by jfberry** [comment]
Now bbdoc is building a web interface to poracle, this is something more suitable for that so closing here
