### ISSUE TITLE
Feature: Galarian Pokedex

### ISSUE THREAD

**Issue by Mygod** [KartulUdus/PoracleJS#149]
Release time: [Wednesday, June 3, 2020, at 1:00 p.m. in your local time zone](https://pokemongolive.com/post/throwbackchallengechampion-2020)

**Comment by gcm-explo1t** [comment]
ALso missing in v3

**Comment by gcm-explo1t** [comment]
Now added in v3 345e12e438b245c14faa99733a7cad3f26042888
