### ISSUE TITLE
Double role notifications 

### ISSUE THREAD

**Issue by marcb1387** [KartulUdus/PoracleJS#150]
## Expected Behavior
when running the command !track pikachu @role only one role should appear when the alert comes out

## Current Behavior
the role is doubled when an alert comes out

## Possible Solution
not sure

## Steps to Reproduce (for bugs)
1. create  an alert with a role in the command
2. wait for alert .......
3. Profit

## Your Environment

* Version used: 4
* Operating System Ubuntu 18.10

**Comment by KartulUdus** [comment]
solved with #159
