### ISSUE TITLE
Issue with Level5 Eggs

### ISSUE THREAD

**Issue by oharewhy84** [KartulUdus/PoracleJS#171]
There is an issue with notifications Level5 eggs for Discord users and channels.

## Expected Behavior
Channel/User setup with "area add <area>" and then "!egg level5". Expected to receive notifications when level5 raid egg in to the channel or via direct message.

## Current Behavior
Admin users are able to setup notifications "!egg level5" and then turn off/on and it continues to work.
Any users/channels that are non-admin that add the area and then "!egg level5" do not receive any notifications. Level 1-4 eggs and raids work without issue for all users.
Users/Channels are in the database correctly and show the same as the admin user so no apparent reason for this happening.

## Your Environment
Running MariaDB:10.3 as poracledb and lastest master branch of PoracleJS.
Notifications to Discord with Discord Bot.

**Comment by jfberry** [comment]
This is an issue with all eggs, can be fixed by editing raid.js to move the 'return jobs' at the end after the close brace instead of before it (I am preparing a pull request).
It only sends to the first match for eggs believe it or not!!

**Comment by oharewhy84** [comment]
Looks good, I'm now getting the Lvl5 eggs on multiple channels. I'll continue to test with that change.

**Comment by jfberry** [comment]
This is resolved in PR185

**Comment by jfberry** [comment]
Can be closed now PR185 is in develop branch
