### ISSUE TITLE
Error Location Command: returns nothing to user using invalid !location command.

### ISSUE THREAD

**Issue by NathanielRMoss** [KartulUdus/PoracleJS#180]
Using SwiftTileServer as my provider, occasionally I get errors like these when "what I assume is" Swift"TileServer can't reverse geocode the address when using !location. PoracleJS throws an error: 

error: location command $location 275 High School Rd NE Ste C-4, Bainbridge Island, WA 98110 unhappy:Cannot read property 'latitude' of undefined {"stack":"TypeError: Cannot read property 'latitude' of undefined\n    at Object.exports.run (/home/ubuntu/PoracleJS/src/lib/discord/commando/commands/location.js:39:68)"}

and returns nothing to the user. My command stroke is $, btw.

## Expected Behavior

Return X reaction or something to the user showing location errored.
Additionally, maybe there's something I'm missing in the tileset, considering 80% of addresses work. Not sure where the tileserver logs are or how to access them within docker, would need help with that. 
Also additionally, maybe be able to look at the return of Swifttileserver's error as a user or in poracle logs.

## Current Behavior

Currently, errored addresses return nothing to the user. 

## Steps to Reproduce (for bugs)

1. Download SwiftTileServer
2. Map of Washington State, USA
2. in Discord to RocketAlert, $location 275 High School Rd NE Ste C-4, Bainbridge Island, WA 98110
3.

## Context

Users think RocketAlert is down because no user feedback of error. 

## Your Environment

* Version used: PoracleJS Develop (#123)
* Environment name and version (e.g. npm 5.6.0, nodejs v7.4.0): 
* Operating System Ubuntu 18.04.4 LTS Linux 4.15.0-112-generic x86_64

**Comment by TiMXL73** [comment]
Just an FYI, Geocoding is done with Nominatim and not SwiftTileServer which is a _**tile**_ server.

You can test your addresses using the official nominatim server: https://nominatim.openstreetmap.org/

`275 High School Rd NE Ste C-4, Bainbridge Island, WA 98110` returns nothing (invalid/unrecognized street name).
`275 High School Road Northeast, Bainbridge Island, WA 98110` does return the requested location.

The correct formatting should always be as available on OpenStreetMaps which may be different from GoogleMaps or RealLife depending on how contributors submitted the information.

**Comment by jfberry** [comment]
This is resolved in PR189 (which adds lon,lat as an option for setting location also). It responds with a shrug if it doesn't find a match.

**Comment by jfberry** [comment]
Can be closed now PR189 is in develop branch
