### ISSUE TITLE
!help command not working 

### ISSUE THREAD

**Issue by marcb1387** [KartulUdus/PoracleJS#205]
## Expected Behavior

should show help page

## Current Behavior

{"level":"error","message":"help command unhappy:fields.flat is not a function","stack":"TypeError: fields.flat is not a function\n    at Function.normalizeFields (/home/user/PoracleJS/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)\n    at MessageEmbed.setup (/home/user/PoracleJS/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)\n    at new MessageEmbed (/home/user/PoracleJS/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)\n    at embedLikes.map.e (/home/user/PoracleJS/node_modules/discord.js/src/structures/APIMessage.js:166:40)\n    at Array.map (<anonymous>)\n    at APIMessage.resolveData (/home/user/PoracleJS/node_modules/discord.js/src/structures/APIMessage.js:166:31)\n    at DMChannel.send (/home/user/PoracleJS/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)\n    at Message.reply (/home/user/PoracleJS/node_modules/discord.js/src/structures/Message.js:602:25)\n    at Object.exports.run (/home/user/PoracleJS/src/lib/discord/commando/commands/help.js:38:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","timestamp":"2020-12-03T14:41:59.692Z"}

## Steps to Reproduce (for bugs)

1. run !help on latest develop branch 
2.
3.
4.

## Your Environment

* Version used:  4
* Environment name and version (e.g. npm 5.6.0, nodejs v7.4.0): node 12.20
* Operating System Ubuntu

**Comment by jfberry** [comment]
This is a node installation problem, please come to discord if still an issue
