### ISSUE TITLE
webhooks not posting data when DTS contains "color" reference

### ISSUE THREAD

**Issue by ColdShadow80** [KartulUdus/PoracleJS#208]
Webhook not posting when DTS contains "color": "{{ivcolor}}",    

Possible origin of problem:  data.ivcolor refers to function  findIvColor(data.iv) witch was present in monster.js file on V3 but is missing on V4/master/develop

https://github.com/KartulUdus/PoracleJS/blob/b02a11b852d36ca0e9695080500fe22e7f20fd16/src/controllers/monster.js#L164

**Comment by jfberry** [comment]
This is in the controller.js ancestor.  But this area is one which has needed change for the recent discord.js upgrade.  
Are you on discord.js 12?
Perhaps can try removing the # in front of the entries for ivcolor in local.json and see if it makes a difference?
@TurtIeSocks understands this color stuff I think?

**Comment by ColdShadow80** [comment]
problem in my setup was fixed by changing color codes in default~.json (or local.json) from the current default HEX format to Decimal:

From:
      "ivColors": [
            "#9D9D9D",
            "#FFFFFF",
            "#1EFF00",
            "#0070DD",
            "#A335EE",
            "#FF8000"
        ]
	
To:
	
    "ivColors": [
            "10329501",
            "16777215",
            "2031360",
            "28893",
            "10696174",
            "16744448"
        ]

**Comment by TurtIeSocks** [comment]
You're on latest develop branch @ColdShadow80 ?

**Comment by ColdShadow80** [comment]
develop branch. New (clean) install made a couple of days ago, a week at most. don't remember if I git pulled in the last 48h.

Extra info:
System: Debian 10
node --version
v14.15.0
npm --version
6.14.8

**Comment by jfberry** [comment]
Perhaps webhook frustratingly requires ints and so this needs converting as it is posted (maybe it doesn’t go through discord.js but posts directly? Not checked yet)

**Comment by ColdShadow80** [comment]
HEX colour codes work on bot posts but break Webhooks (which work with Decimal) 

Decimal work with Webhooks but break bot posts (which work with HEX)

**Comment by jfberry** [comment]
Have pushed a change which converts the hex to decimal in the webhook post, let me know if this fixes it for you (it did for my test case)

**Comment by ColdShadow80** [comment]
Confirmed fix. Webhooks work as expected and so does normal tracking
