### ISSUE TITLE
Feature : Per-User language settings

### ISSUE THREAD

**Issue by bbdoc** [KartulUdus/PoracleJS#211]
## Expected Behavior

Locale settings should be user-based instead of being set for the whole instance.

## Current Behavior

language is currently defined at the global level, so only way to allow for multiple language is to launch 2 instances, maintain 2 DBs and have 2 different Bots. 

```
    "locale": {
        "timeformat": "en-gb",
        "time": "LTS",
        "addressFormat": "{{ streetName}} {{ streetNumber }}:",
        "language": "en"
    },
```

## Possible Solution

Moving language settings at the user level (so in `humans` table) would allow to run only one DB and for each user to chose their own preference.

**Comment by jfberry** [comment]
In progress

**Comment by jfberry** [comment]
This has now entered testing (pre pull request), please get in touch with me on discord if you can help to test this one

**Comment by jfberry** [comment]
Pull request now available with multi-language support

**Comment by jfberry** [comment]
Merged
