### ISSUE TITLE
Feature : Rework Logs

### ISSUE THREAD

**Issue by bbdoc** [KartulUdus/PoracleJS#213]
## Current Behavior

Poracle is currently logging a lot of information, but most of the time information logged is completely useless to real troubleshooting. It should log less stuff, but more useful stuff.

Some examples :

```
{"message":"Wild encounter 7079506970964088000 was sent again too soon, ignoring","level":"debug","timestamp":"2020-12-07T16:27:14.769Z"}
{"message":"Wild encounter 7079506970964088000 was sent again too soon, ignoring","level":"debug","timestamp":"2020-12-07T16:30:36.674Z"}
```
no idea what `was sent again too soon` means and how this could be useful to any troubleshooting. Should be sent only to a debug log when debug is activated in config.

This is a very big amount of messages :
```
grep -c "was sent again too soon" debugLog*
debugLog1.json:116787
debugLog.json:79099
```

Console log is currently useless as it doesn't give any information which would let an admin troubleshoot an issue, typically :
```
Hoothoot appeared and 0 humans cared
```
This log line should at least contain a timestamp + encounter_id so it can be tracked down to something.

On the opposite, it would be very useful to have a message log (which option to enable/disable it). Ideally a different one for discord and telegram, which would log the whole message sent :

```
{"message":"Telegram sending message {\"content\":\"***Un Raid 6 contre Blizzaroi Mega à démarré !!!***\\nArène : Calvaire, Aische \\nSe termine à: 16:22:50 \\n\\nAttaque Rapide: Tranch’Herbe 🌿 \\nAttaque Chargée: Éco-Sphère 🌿 \\n \\n\",\"sticker\":\"https://mydomain.com/telegram/monsters/460_935.webp\",\"location\":true,\"webpage_preview\":false} / connection to bbdoc 9999999999","level":"warn","timestamp":"2021-01-09T14:36:10.782Z"}
```

Other remarks :
- Debug log should be configurable and disabled by default.
- Webhook log should be configurable (and probably also disabled by default).
- A `discord.json` log would be very useful. It should contain a line per message sent to discord with at least timestamp + encounter_id + discord_id so that an admin can track down a message received or not by a user.

**Comment by jfberry** [comment]
Consider issue 255 alongside this

**Comment by jfberry** [comment]
Webhook log should break down into different files different hook types
discord and telegram outbound stats log
Encounter id/ other id present in log messages that relate to hook processing to enable tracing of problems
Ability to increasing logging from command line as well as config?

**Comment by jfberry** [comment]
PR in, please comment on that so we can fine tune logging

**Comment by jfberry** [comment]
merged
