### ISSUE TITLE
Bug : Truncated encounter_id in logs

### ISSUE THREAD

**Issue by bbdoc** [KartulUdus/PoracleJS#214]
All encounter_id in logs are currently being truncated/rounded, probably due to a wrong data type :

e.g.:
```
{"encounter_id":8427357231974403000,"pokemon_id":261,"spawnpoint_id":4931631954051,
```

I checked in MAD tables and actual encounter_id is `8427357231974403189`, not `8427357231974403000`

```sql
MariaDB [mad]> select encounter_id from pokemon where encounter_id like '84273572319744%';
+---------------------+
| encounter_id        |
+---------------------+
| 8427357231974403189 |
+---------------------+
1 row in set (0.041 sec)
```

**Comment by jfberry** [comment]
I found this library which claims to fix the problem, no idea on performance issues or whether it would just drop in cleanly but leaving it here until someone has time to look https://github.com/josdejong/lossless-json

**Comment by Petap0w** [comment]
this seems not to be the case with rdm:
`encounter_id` in webhooks.json logs from Poracle are matching the `id` in rdm pokemon table.

**Comment by jfberry** [comment]
Does RDM send the encounter_id as a string?

**Comment by jfberry** [comment]
Seems like encounter_id is a string in RDM. We should try to get upstream MAD to fix and send us as a string this because the alternative is apparently much slower and I'm not giving up parsing speed for this (although it is annoying I agree)

**Comment by jfberry** [comment]
Malte has had his PR accepted into MAD - so this issue is resolved!
