### ISSUE TITLE
Feature: Park User

### ISSUE THREAD

**Issue by bbdoc** [KartulUdus/PoracleJS#215]
Admin able should be able to `!park` a user.

At the moment the only way to disable access to a user is to `!unregister` the user. But unregistering removes all info linked to that user in all DB tables, meaning that if user gets access to Poracle again next time, he needs to reconfigure all their alarms.

It should be possible to temp disable a user without losing all tracking info so he can get back with the same tracking when enabled again.

**Comment by jfberry** [comment]
Would this be like them issuing !stop?

I wonder whether a nice idea would be to do something like:
!as bbdoc stop
or
!as bbdoc tracked
(to see a user's tracked)...

**Comment by bbdoc** [comment]
Not as `!stop` can be overwritten by user. I would like the admin to be able to disable a user without the user being able to re-enable himself. But globally that's just the same feature as stop with an additional field in DB and only accessible to the admin only.

**Comment by ColdShadow80** [comment]
Basically, we could even unregister the user, but keep the tracking record active. bbdoc's idea is also cool, but I wonder what the right "trigger" for it would be.
There is probably no need to clean the DB of the user records and force them to reconfigure all the trackings if they return later.

**Comment by t00fan** [comment]
> Would this be like them issuing !stop?
> 
> I wonder whether a nice idea would be to do something like:
> !as bbdoc stop
> or
> !as bbdoc tracked
> (to see a user's tracked)...

I def like the idea of seeing the tracked and config settings for other users via a command.  There are a lot of times where I end up asking them the output of !tracked and if this is simple enough to add, it would be a time saver.  Once again, thank you for maintaining this and keeping it going. Much appreciated.

**Comment by jg92** [comment]
While at it... Would be great to add new flag to config, lets say `disableInstead` (with default `false`) to "disable" user instead clear all user trackings.

**Comment by lenisko** [comment]
While at it... Would be great to add new flag to configuration lets say `disableInstead` (with default `false`) to "disable" user instead cleaning all user trackings. This could be helpful once user loses his role and comes back fairly fast.

**Comment by kamieniarz** [comment]
We could have 2 variables in config: `enableDisablingUsers` to enable that option and `removeDisabled` to set removing users from database after x days of losing access (0 = don't remove). Also this feature could come with commands as mentioned in comments so sending (as an admin obviously) `!disable username` would disable user and also ignore his `!poracle` messages and DMs if possible
