### ISSUE TITLE
Dynamic loading of DTS & Geofence file

### ISSUE THREAD

**Issue by t00fan** [KartulUdus/PoracleJS#217]
Since Poracle currently resends all the active notifications on a restart, it is best to avoid restarts as much as possible. However changing DTS or adding a new location to the geofence file currently requires a reload.

It would be great if Poracle could detect changes in those files and dynamically load them without a restart of the entire service.

## Expected Behavior
Admin makes changes to dts.json, and saves the file. Poracle detects the change and loads the new DTS or geofence file.

## Current Behavior
Currently the Poracle service has to be restarted to pick up new DTS or Geofence.

**Comment by jfberry** [comment]
petap0w tried this, but it had a number of problems and would be quite hard to get exactly right given the current poracle architecture: there is now a PR in to save the event cache and message cleaning which means a restart is less painful, please test and feedback

**Comment by jfberry** [comment]
Message cleaning & duplicate cache retention PR in testing that will close this issue

**Comment by jfberry** [comment]
Merged
