### ISSUE TITLE
Configuration option to disable new 'everything' behaviour

### ISSUE THREAD

**Issue by jfberry** [KartulUdus/PoracleJS#218]
Provide a new behaviour configuration section for this and future optional behaviour.  In the !track command treat it as though the 'individually' flag is set always if this behaviour is enabled. Treat no entry in the config as off, and update the default config file to include the new section.

**Comment by JuanFML** [comment]
Hi! I am new here and I wanted to do this as my first issue, could I have some guidence on where to start?

**Comment by Petap0w** [comment]
Added in pr221 under commit [55bafdb](https://github.com/KartulUdus/PoracleJS/pull/221/commits/55bafdb8a9d31e1b7348f2aec62ee5c8372001b7)

**Comment by jfberry** [comment]
merged
