### ISSUE TITLE
Feature : Allow quests tracking to track mega-energy for a specific Pokemon.

### ISSUE THREAD

**Issue by bbdoc** [KartulUdus/PoracleJS#220]
Allow quests tracking to track mega-energy for a specific Pokemon.

At the moment you can only track based on the amount of mega energy, but most people don't care about the amount mega-energy if it's not for the pokemon they need it.

This would request the addition of a new column in DB as currently, there is only one `reward` column, being used both for the pokemon_id (reward_type 7) and for the amount of mega-energy (reward-type 12). Pokemon_id would need to be stored in a separate field together with the amount of energy available in reward.

**Comment by jfberry** [comment]
PR-237 should close, can you confirm bbdoc?

**Comment by bbdoc** [comment]
Didn't have time to check the PR yet... I guess we can close as soon as it has been merged

**Comment by jfberry** [comment]
Now merged
