### ISSUE TITLE
Feature Request:  Config option to Force Distance Paramater in trackings.

### ISSUE THREAD

**Issue by kbtbc** [KartulUdus/PoracleJS#222]
In my setup, I don't use "areas" at all, and would like all !track commands to be required to have a distance 'd' paramater or get rejected. 

A simple 'Require_Distance' config variable or similar where no areas are in use would be nice.   

(There may be other benefits to not executing area checks in performance where they are not required.)

**Comment by Petap0w** [comment]
maybe instead of rejected to be registered with a default value set in your config?

**Comment by kbtbc** [comment]
That would be good, a default value.   Also, having a 'maxmium' distance config would be nice (as is I handle with sql task lol)

**Comment by Petap0w** [comment]
that's now included in pr221, commit [724c686](https://github.com/KartulUdus/PoracleJS/pull/221/commits/724c68618296d07732335aac176ce8891616dd92)

**Comment by jfberry** [comment]
merged
