### ISSUE TITLE
[Feature Request] DnD (Do Not Disturb)

### ISSUE THREAD

**Issue by lenisko** [KartulUdus/PoracleJS#223]
Add DnD (Do Not Disturb) to PoracleJS bot.
This would save some webhook calls and as well some nerves / frustration.

First of all it might be good to state which version would be better in long term.
Easy one is as simple as setting static hours range for all days and switching it on / off. Might be good for starter.
Hard way would be based on schedules, where user can define more than one DnD rules for a week days.

# Easy Way
## Expected Behavior
* `!dnd <hours_range>` - enable DnD schedule on current user for provided hours range.
  * `!dnd 22-8` - enable DnD from 22:00 till 8:00 everyday
* `!dnd off` - disable DnD schedule for current user.

## Notes
* Times should be handled in UTC ?? otherwise we would need to collect user timezones.

## DB Changes Proposal
Add a default empty list `[]` to `humans` table names `dnd`.
When enabled the list would become `[start_hour, end_hour]`.

---

# Hard Way
## Expected Behavior
* `!dnd on` - enable DnD schedule for current user.
* `!dnd off` - disable DnD schedule for current user.
* `!dnd add <week_day_range> <hours_range>` - Add DnD on current user for provided week days and hours range.
  * `!dnd add 1-5 22-14` - DnD from Monday to Friday from 22:00 till 14:00.
  * `!dnd add 6-7 0-6` - DnD on Saturday Sunday from 00:00 till 6:00.
 * `!dnd list` - List all added DnD's for current user with `id`.
 * `!dnd del <id>` - Remove DnD with provided `id` for current user.

## Notes
* Split days range by `-`, first argument needs to be smaller then second (easier to parse later on).
* `on / off` sounds looks better than `start / stop` I think ,-)
* Times should be handled in UTC ?? otherwise we would need to collect user timezones.
* Cron for cleanup based on last user activity?
* Make sure we validate user_id upon removal.
* Make it clear how days/times range work. For example we have schedule rule `1-2 23-5` Monday, Tuesday from 23:00 till 5:00 - we are starting at Monday 23:00 and stopping at Tuesday 5:00 or starting at Monday 23:00 and stopping at Wednesday 5:00?

## DB Changes Proposal
Add new table `dnd_schedule`
```
id - used to removal (auto increment)
user_id - obvious
added_at - datetime of schedule addition, might be useful for cleanup? for example we keep those for 3 months after last user activity?
weekday_start - number of week day we start dnd rule
weekday_end - number of week day we stop dnd rule
hour_start - start of dnd hour
hour_end - end of dnd hour
```

**Comment by jfberry** [comment]
I think this is an excellent idea.  I think it may be easier than you suggest - if there were just a single json dnd time string on the humans table it would then be easy for the code to check rather than have some more complex relational work either at time of finding interested humans or later...

**Comment by jfberry** [comment]
I also think a middle way might just be to say you can only specify a DND range per day (or all days) - or maybe it should be the other way round the alert times?

!alerttime monday 18-23
!alerttime sat 08-23

if there is no alert time set for a day, then it is all day
(I was just thinking that you may want to be not disturbed twice in a day, at the start and at the end and positive alert time might be better)

**Comment by lenisko** [comment]
>  I think the hard way may be easier than you suggest 

Hardest part is parsing provided arguments :-)

> If there were just a single json dnd time string on the humans table it would then be easy for the code to check rather than have some more complex relational work either at time of finding interested humans or later...

I like your idea with single list to keep all dnd rules. What I was thinking and got a bit blinded by more complicated schema was possibility of abuse. Some additional checks would have to be performed at the time user is adding DnD. For example:
* Monday 1-5, Monday 5-10 - are two separate rules but we can actually merge it and make one rule Monday 1-10 from code side
* Monday 1-10, Monday 2-5 - second rule shouldn't be allowed as it's pointless

Less rules is equal to less checks in each loop. As without it user could add a LOOT of rules and each rule is slowing down loop.

> I also think a middle way might just be to say you can only specify a DND range per day (or all days) - or maybe it should be the other way round the alert times?

I was rather thinking about same case as we have on  iPhone/Android  so exclusion for alerts. It's named Do Not Disturb (DnD) - hence I just reused that name. Idea with `alerttime` command is breaking change by the logic - but yes we can create migration to database to enable all days by default. Still I think exclusion is better idea here.

**Comment by jfberry** [comment]
I was thinking that if a day wasn't present the code would just alert always - so no values would need to be in the column on upgrade.  positive alert time or negative do not disturb is probably not that much more complex from a code point of view - just for DND you really need two periods in the day (early hours and evening). if you are doing a day by day

**Comment by lenisko** [comment]
Hmm.. I won't hide the fact I still prefer exclude approach but your arguments are strong.
How about compromise? like adding simple switch flag which would allow to pick between include/exclude mode?
From code side all it would do is to cast negative or not on the check (I think).

**Comment by jfberry** [comment]
If you’re coding it you can do what you want :-)

—
James Berry, m. 07768 021031


________________________________

**Comment by jfberry** [comment]
If you're coding it, you can do what works for you ;-)

**Comment by jfberry** [comment]
Another variant suggested by another user
Have a series of schedules which can be changed - eg schedule 1 has these mons tracked, at this location, in these areas; schedule 2 different
There then could be timings associated with a schedule.

Thinking about this having a schedule id on humans for current schedule; and this id in the tracking tables would allow joining to get the current schedule for the controllers quickly

Users could switch schedule with a /schedule command, and there could be an event which ran eg every 15 mins to check if there was a need (based on some timing rules) to switch schedule which will update the schedule no/area/location

**Comment by philcerf** [comment]
Would be nice if one could set times **per** tracking rule... i.e. I always want to be woken up for some super rare IV100% mon.

**Comment by kamieniarz** [comment]
As above - if DND would be implemented it could also work with tracking profiles or ath like that. So basically we could set multiple profiles like `work` and `home` with different areas/locations and set their timeframes
