### ISSUE TITLE
Tracked invasions does not show distance.

### ISSUE THREAD

**Issue by boby360** [KartulUdus/PoracleJS#235]
Title says it all.
If you use -tracked and look at what invasions you have set, a distance is not shown.

## Expected Behavior
Show you the distance that you have set in the output of command.

## Current Behavior
When -tracked is used, it does not show you the distance.
only Gender: and Grunt type:

## Possible Solution
Bug people who know things.

## Steps to Reproduce (for bugs)
-tracked

## Context
Good question.

## Your Environment
Not relevant i'm sure.

**Comment by Petap0w** [comment]
<img width="384" alt="Capture d’écran 2020-12-29 à 09 54 29" src="https://user-images.githubusercontent.com/47784174/103271948-e125e080-49bb-11eb-85b4-f8d4f2e4c250.png">
You just need a distance set in your tracking and it'll show
