### ISSUE TITLE
Feature Request: Area Role Manager 

### ISSUE THREAD

**Issue by RagingRectangle** [KartulUdus/PoracleJS#247]
When a user adds/removes an area have the option to automatically add/remove a corresponding role.  Would help clean up the channel list for people if you have a lot of areas.

**Comment by SenorKarlos** [comment]
Hijacking and Expanding on this request, mimicking the function of WhMgr's zone role management.

In mine and many other discords, roles are used to show/hide sections of content (in my case alert channels) based on the Zone geofences I've already established. Managing this manually when people lose a donorRole is cumbersome at best.

In the other app, the command !feedme (or Roles section of it's UI) allows users with the donorRole to assign and remove these roles from themselves, and the bot automatically removes these roles upon donorRole loss. The command name was to be replaced with something more sensible but development has paused over there. feedme comes from the concepts start, where the role/subscriptions were tied together. something like !role add/remove RoleName would be better.

To take it a step further, I would like (if accepted) 2 options built in. The first being a database table which stores selected roles for restoration on donorRole being given back, and the ability to specify per server how many roles any one user may have. The config could look something like this:

{
  "areaRoles" : {
    "serverID" : {                //Numerical ServerID
      "allowedRoles": 0,      //Number of roles allowed, 0 for unlimited
      "roleNames": [
        "Area1",
        "Area2"
        ]
    },
    "serverID2": {            //repeat for as many servers as used
    }
}

**Comment by SenorKarlos** [comment]
Everything but one option has been satisfied in PR #620 😄 Thanks and Kudos!

Just need a database table that can remember users selections for restoration when 'disable-user' is the preferred reconciliation method. Keep it consistent with other functions, where they can just pick up exactly as they left off when unsubscribing and coming back.
