### ISSUE TITLE
Feature Requests : Stats

### ISSUE THREAD

**Issue by bbdoc** [KartulUdus/PoracleJS#255]
Please add minimal stats to Poracle, mainly to allow followin-up on the number of messages sent per channel/user and total messages sent to Telegram/Discord.

A very easy and flexible way would be to add a stats table and log all messages sent to it with Datetime, ID, type. 

Another way would be to add an horodated messages.log file.

Content of the message is not really needed for stats but additional info could help for troubleshooting purpose (typically the encounter_id).

**Comment by kamieniarz** [comment]
I love the idea. That's how it worked in v3 - number of total alerts sent was in humans table

**Comment by jfberry** [comment]
Kartul removed it from v4 for performance reason (the total alerts count, anyway).
Whilst theoretically quite easy it would certainly need to be optional!

**Comment by bbdoc** [comment]
Maybe just a log file with all sent messages then so it doesn't impact performance. If we can have one file per day it becomes easy to create some basic stats out of it. Add to that an option to disable webhooks.json logs, which I think are less useful than being able to get info on message sent, and that will in total generate far less logs than today 😉

**Comment by jfberry** [comment]
Can you consider this request when evaluating the logging PR?

**Comment by jfberry** [comment]
Log files work, thanks for alarm stats initial contribution!
