### ISSUE TITLE
Track lures

### ISSUE THREAD

**Issue by jfberry** [KartulUdus/PoracleJS#257]
Should be an ability to alert on lures

!lure everything
!lure glacial
!lure mossy
!lure magnetic
!lure standard

Would need to support distance and areas
Anything else...?

**Comment by ColdShadow80** [comment]
Nope.
That's it. Nothing else is left to track

**Comment by Dewpg** [comment]
Id be a big fan of this, the hooks are sent already, seems simple enough.

**Comment by jfberry** [comment]
The reason I raised the issue is because I would like to see this too - so I'll do it eventually if no-one beats me to it!
