### ISSUE TITLE
Use Discord's CDN to host Static Maps on

### ISSUE THREAD

**Issue by ccev** [KartulUdus/PoracleJS#260]
When using a self-hosted Tileserver, it might be a little slow for users to load the images in embeds. Especially when looking at older messages where the Static Maps aren't cached anymore.

Additionally, it's better to avoid sharing the Tileserver URL with others, since anyone could use it to generate their own tiles / Static Maps (though this shouldn't be too big of a problem for most users)

Since Poracle is a Discord bot, a good solution to these problems is to host Static Maps on Discord's CDN.

It could work as follows:
```
  - Have a config option like "host_channel_id"
  - If that option is empty, just continue like we're used to
  - If using tileserver and the option is filled:
    - Fetch the Discord channel using the ID
    - Make a POST request to tileserver.com/staticmap/template using the proper data
    - This will return the map image in bytes. Convert this reponse to an image format discord.js accepts
    - Send a message to the channel with the image in its attachments
    - Read the attachments of the message and use its URL as the {{{staticmap}}} DTS option
```

**Comment by jfberry** [comment]
This is an awesome suggestion. Have you seen any (javascript) code that does this that we can steal from?

**Comment by ccev** [comment]
I have not seen any code that does this, just Python.

Before pregenrating was a thing, my Stop Watcher Map URLs were too long for Discord, so I used Imgur to host the images. However, you need a phone number to sign up, which sucks.
I'd recommend against using other CDN providers. That'll just make things more complicated than they should be.

No idea how Telegram works, does it not have a CDN similiar to Discord?

**Comment by muckelba** [comment]
Telegram has an internal CDN wich is not really accessible

**Comment by JabLuszko** [comment]
Discord is using Cloudflare for those embedded images (until you manually click "Show original" that loads direct URL) - you will get one request per one Cloudflare POP that your users are using.

>  Especially when looking at older messages
Increase caching headers on your tileserver and let Discord CDN/CF handle those? You shouldn't really care about it being slow for older (more than 1h?) mons. 

Not really sure if converting image to bytes and uploading this "inline" is a good idea. With bigger/split minimaps it can go to 200+ KiB and sending that kind of data with every alarm seems kinda stupid?

**Comment by ccev** [comment]
> With bigger/split minimaps it can go to 200+ KiB and sending that kind of data with every alarm seems kinda stupid?

Is a Discord CDN png not the same size as a static map straight from the tileserver?

**Comment by jfberry** [comment]
Poracle doesn't have to download the static map from the tileserver though, it just gets a URL from it with the pregenerated PNG.  This would require downloading the full PNG and pushing it somewhere else and then rewriting it. 
I can see why long term off-site storage of your generated tiles would be attractive though

**Comment by jfberry** [comment]
You have done this :-)
