### ISSUE TITLE
Removal of Invasion tracking doesn't work as expected

### ISSUE THREAD

**Issue by plinytheelder** [KartulUdus/PoracleJS#264]
Usually not a problem because 99% of users hate doing Rocket Battles. But with the recent Event, users registered for Rocket Invasions and have no idea how to remove them.

With normal notifications the following commands work:
`!untrack everything` or `!raid remove everything`, etc.

But for Rocket Invasions,
`!invasion remove everything` does not work.

Users have to remove the notifications one by one for it to register correctly.
`!invasion remove dark`, `!invasion remove ice`, etc.

**Comment by Petap0w** [comment]
see PR 266

**Comment by jfberry** [comment]
Merged
