### ISSUE TITLE
multi message mode for TG-bot replies like from /help

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#282]
Hey.

The following is absolutely not that important,... so just close it if you don't see an easy way.

I recently started with a localised version for a `/help` text for our community here, and quickly ran into the problem, that Telegram has a pretty small maximum message size, and apparently also a maximum number of format codes it accepts per message.

So would be nice if one could set the reply for such commands to be split into multiple messages from the bot, cause when one wants to explain "all" aspects of poracle, one can easily hit the limit.

Cheers!

**Comment by philcerf** [comment]
Alternatively,.. one could perhaps allow
`/help command`
with a different output text per command.

Seems even nicer.

**Comment by jfberry** [comment]
help is now split into 1024 byte chunks for telegram (in multilang PR)
Hope this helps!
