### ISSUE TITLE
some commands show to have succeeded, while they did not

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#287]
Hey.

When stumbling over the issue with the `_` in form names, I've mentioned in #278, I've also noted that commands like:
`/track Icognito formX formQ formQuestion_mark formExclamation_point`
get the OK reply from the bot, while in fact the command only succeeded for the forms X and Q.

Cheers.

**Comment by jfberry** [comment]
Telegram had problems with _ for responses, which is resolved in multilang.
The command processing has changed somewhat for this, can you repeat the test in that branch so we can track down any issue here?

**Comment by jfberry** [comment]
Closed as fixed (well it doesn't tell you about unrecognised things but the underscores work)

**Comment by philcerf** [comment]
Damn I knew I've already had an issue about that... haven't seen that you've closed this one, so I've opened another one in the meantime. Hope that's ok?
