### ISSUE TITLE
Bot no longer accepts zip code to update location.

### ISSUE THREAD

**Issue by kbtbc** [KartulUdus/PoracleJS#290]
The previous behavior allowed sending your US zipcode to the bot to set your location.  It was a short, working option for user. 

Since, a recent update the bot now complains when trying to set your location this way:
![image](https://user-images.githubusercontent.com/7109934/105739095-be78e000-5f05-11eb-85eb-dfdb4b1eb233.png)

Please restore the previous functionality.

**Comment by Petap0w** [comment]
does it works if you give zip code followed by USA ?

**Comment by Astu04** [comment]
Postcode + country works in my case (Spain). 
Only postcode does not. 
`if (args.length == 1) {`
It complains if there is only one word.

**Comment by Petap0w** [comment]
that's not the purpose of location in the first place tho.. if you give only a city name (or postcode) that'll locate you wherever in that "administrative" boundary, which could be way off your actual position. Then a simple proximity track d500 within walking range would not mean anything.
it would be wiser to educate the users with some details in your welcome/help message that a street name at least would get them closer to what they need.

**Comment by Petap0w** [comment]
pushed a PR for this

**Comment by kbtbc** [comment]
I understand and conveyed using more precision than zip code, and yet it's still was some users prefer (really only one guy who found if efficient to switch between work and home).    And yes, it does work if you add the state or USA after the zipcode.   Wasn't a huge deal, and so thanks for the PR to allow to work as before.  Will check it :-)

**Comment by kbtbc** [comment]
... btw, this reminds me of a small feature request from a user I'd pass along here, and that is the ability to alias locations.   So, `!location home` and `!location work` could be defined...  Cheers

**Comment by jfberry** [comment]
merged into develop
