### ISSUE TITLE
provide dts fields that prevent numbers from becoming links

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#292]
Hey.

Telegram (or is it Android itself) tries to be smart and converts numbers to tel: links, which is kinda annoying.
It does so after any at least two consecutive digits and it seems the links are sometimes even made with single letters(!) in between, even when having something like `99 x 9` will become a link.

I've tested a bit around and it seems one can prevent this, by surrounding each digit with either of:
‍`U+200C ZERO WIDTH NON-JOINER`
`U+200D ZERO WIDTH JOINER`
of which it seems to me the later is more appropriate (when it comes to word wrapping and the like).

Also, because of cases like the `99 x 9` described I think it has to be really **surrounding each diget**, i.e.
`\u200D1\u200D2\u200D3\u200D`
instead of just
`1\u200D2\u200D3`

Not really sure how to best solve this?
Generally surround any numbers in any of the {{foo}} fields? (Cause it's not only e.g. {{iv}} or {{atk}} that can contain number (think of Porygon2).
Provide additional fields just for those ones where we know they may contain numbers (like a {{iv.escaped}} or so?

Cheers.

**Comment by jfberry** [comment]
This could be implemented with a handlebars function eg:   {{preventTelegramPadding atk}}
See lib/handlebars.js
