### ISSUE TITLE
DTS in wiki V4 RDM

### ISSUE THREAD

**Issue by Dewpg** [KartulUdus/PoracleJS#297]
DTS updates:

gymName should return gymname
cp20 and cp25 should return best raid boss cps at these levels. It doesnt.

Wiki needs to be updated for RDM V4 as it currently isnt.  Thanks for coming to my TED talk.
Ill add things here as I find them.

**Comment by muckelba** [comment]
https://github.com/muckelba/poracleWiki/issues use the correct repository pls

**Comment by jfberry** [comment]
{{calculateCp baseStats 20 15 15 15}} for level 20 15/15/15 for example

**Comment by jfberry** [comment]
Please PR to the above repository doc changes, or raise issues there
