### ISSUE TITLE
Allow users to use `!backup` and `!restore`

### ISSUE THREAD

**Issue by kamieniarz** [KartulUdus/PoracleJS#300]
As simple as that - a feature request to let users use these commands to backup their settings and restore them at any time

**Comment by jfberry** [comment]
I have been thinking about this.
I was thinking that users could only backup and restore their own settings privately to them (saves worrying about naming and collisions, and abuse of names)
But administrators might be able to indicate a particular backup was available to all, so would appear on everyone's list?

**Comment by jfberry** [comment]
Transferred to wishlist-voting
