### ISSUE TITLE
Case sensitive {{areas}}

### ISSUE THREAD

**Issue by pogoteambrindisi** [KartulUdus/PoracleJS#302]
- Right now area texts are converted to lowercase but it would be nice for them to be printed correctly in messages at least when called as a DTS with {{areas}}. Example: right now Chicago becomes chicago.
- A space in the declaration of an area, say "New York", is currently converted to underscore (new_york), but this is then impossible to track with /area add in Telegram.

**Comment by jfberry** [comment]
Agree that it would be nice if {{areas}} reflected capitalisation.
For the second point are you saying `/area add new_york` (which is what I would expect to work) doesn't?

**Comment by jfberry** [comment]
Recreated second issue, will be fixed in multilang pr

**Comment by jfberry** [comment]
Second issue is now fixed

**Comment by jfberry** [comment]
Perhaps you can do {{capitalizeAll areas}} ?

**Comment by jfberry** [comment]
Closed, moved to wishlist-voting
