### ISSUE TITLE
images for some Pokemon forms not correctly displayed

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#304]
Just for the records before I forget about it:

This happens at least with the images used within staticmaps.... but I guess it could also affect the stickers.

What happens is, that e.g. the images for forms of Unown are not correctly found. For example, Unown A should be ID 201 with form ID 1.
Some(all?) tilesets, at least the one from PokeMiners use however this e.g. `pogo_assets/Images/Pokemon/pokemon_icon_201_11.png` as the one for Unown A.

Not sure whether this is an issue in the tile server or poracle, but I guess it's rather the later?

RocketMAD, e.g. solves this by having an additional field in their JSON file, i.e. `static/data/pokemon.json` has something like:
```
  "201": {
    "name": "Unown",
    "types": [
      {
        "type": "Psychic",
        "color": "#f85888"
      }
    ],
    "forms": {
      "1": {
        "formName": "A",
        "assetId": "11"
      },
      "2": {
        "formName": "B",
        "assetId": "12"
      },
      "3": {
        "formName": "C",
        "assetId": "13"
      },
```

Not sure who Poracle will/should handle this, as it would need to handle really both, the actual form ID and the asset ID.

I guess this affects also #278, where the script would need to add the asset IDs to the generated JSON (and it seems @ccev's PogoData would in fact export that information).

Cheers.

**Comment by ccev** [comment]
You should be using an optimized iconset. go to the pmsf server and type `.sprite`. it's mainly whitewillems pogoassets and Nplumbs Home/Shuffle icons.

ingame assets are based on asset values/suffixes that are only available in the Gamemaster. The optimized assets use form IDs to make it easier to work with.

**Comment by jfberry** [comment]
and it feels like we might have a new icon file format with fallback before too long and that'd be the right time to invest in working out how to get best support for that in poracle (including on tiles)

**Comment by Petap0w** [comment]
can be closed: updated monsters.json uses both gamemaster and pogo protos for pokemon ID and associated form ID
Unown A form is 1 according to protos:
https://github.com/Furtif/pogo-protos/blob/73c48a67dfbba759d4f84cd633a005eb7e8780d3/proto/Rpc/Rpc.proto#L12427

assetbundleid shouldn't be used in icon naming, only form ids.
