### ISSUE TITLE
Rocket Leaders repeat alerts every 90 minutes

### ISSUE THREAD

**Issue by Debaucus** [KartulUdus/PoracleJS#305]
## Expected Behavior

Expected: Countdown to 10PM local time. 

## Current Behavior

Current: Countdown to next hour. 

![image](https://user-images.githubusercontent.com/60629996/106300277-3456b180-624e-11eb-83e3-8740e0b416ed.png)

## Steps to Reproduce (for bugs)

1. Set Rocket Leaders channel.
2. Wait.
3. ???
4. Bug found.

## Your Environment

* Version used:
* Environment name and version (e.g. npm 5.6.0, nodejs v7.4.0):
* Operating System

**Comment by jfberry** [comment]
Do you have a webhook for this? If the webhook tells us the invasion stops at 22.00 I'd agree with you. If the webhook (which I assume is based on game data) tells us it stops earlier I'd expect us to honour that.
What does that say? (I guess it must get the 22:00 from somewhere, or is this hardcoded in your DTS?) Is this MAD or RDM?

**Comment by Debaucus** [comment]
- Not a webhook, invited bot and used `!channel add` for initial setup in channel. Added the leaders though the Web Panel in admin.

- I am using PoracleJS default in dts.json

`              "fields": [
                  {
                      "name": "**Invasion Expires**:",
                      "value": "{{time}} | {{tthm}}m {{tths}}s"
                  },
`

- Using MAD.

**Comment by jfberry** [comment]
Not a webhook to discord, but is a webhook from MAD to send you the data. 
I run mad as well so looked in my logs. My initial investigation shows the hook coming in with a 10pm end time.
Poracle's cache though is 90 mins so a repeat notification would trigger another alert.
Just tried to debug on my machine and unfortunately only 90 mins away from 22:00 so will need to wait for tomorrow to see why the calculation is not working

**Comment by jfberry** [comment]
Ok, looks like calculation is fine.  You don't have {{tthh} to display hours in your dts.
However, I suspect that 90 minutes later you are getting another alert? Is that the case?

**Comment by Debaucus** [comment]
> 
> 
> Ok, looks like calculation is fine. You don't have {{tthh} to display hours in your dts.
> However, I suspect that 90 minutes later you are getting another alert? Is that the case?

Hours now display, thank you!

Yes it does look to be every 90 mins the alert is triggered, I can post examples with time for confirmaition if needed.

**Comment by jfberry** [comment]
I know exactly what it is - the cache for duplicates lasts 90 mins - which is fine for most events but not invasions. I will fix it by having a longer invasion cache specially.

**Comment by jfberry** [comment]
This fix is part of the multilang PR

**Comment by jfberry** [comment]
Merged
