### ISSUE TITLE
Staticmap doesn't load from time to time

### ISSUE THREAD

**Issue by kamieniarz** [KartulUdus/PoracleJS#310]
## Expected Behavior
So generally when there's {{staticmap}} in dts or just whatever that generates map using tileserver it just should generate it no matter what - even if there's like 100 humans who cared about that specific mon it should still generate staticmap for every single one (except when tileserver is down but it's not the case).

## Current Behavior
Sometimes staticmap just won't generate - notification comes without it. But it's not like it's not generated at all - I have multiple channels and my own notifications and if there's no staticmap for a specific mon the exact same mon has staticmap on another channel (I have cannel for all cities in one and channels for each city so notifications are always duplicated so I can check if map was generated or not). It's pretty random, it's never like it didn't generate for none of my channels - if it happens it's always like static map is missing somewhere but it's present somewhere else. I have no errors in poracle nor in SwiftTileServerCache - everything is stable and works as it should be.

## Possible Solution
Maybe some kind of (optional) doublecheck for staticmap in generated notification? I'm not sure how the whole notifications disctibution process works so I can't say if doublecheck could be possible but if not maybe there could be any other fix for that? I'm looking forward to it and I'm ready to test any kind of fix

**Comment by Petap0w** [comment]
This is a discord issue not a Poracle issue. nothing to do here

**Comment by kamieniarz** [comment]
Oh so it's a known one? I thought no one experience that cause I mentioned that issue few times some time ago and no one confirmed to have same issue 😬

**Comment by jfberry** [comment]
If you have no errors in your logs then staticmap is probably working.  I had problems with discord until I managed to get the right regional blocking behaviour as they do some external checks as well as direct from the client
We could start logging the URL generated in a debug log and you could spot check them to see if it is a poracle issue in the future (and since I am looking at logging that sounds like a sensible way forward as part of that)

**Comment by kamieniarz** [comment]
Well actually some time ago I had issues with my server. Lets say it wasn't responsive engouh to handle some things and also my map was loading slow. Due to that staticmaps weren't generating in notifications at all. There was no error in poracle or in tileserver so looks like it wasn't discord related. I think some kind of double-check could be added if possible

**Comment by jfberry** [comment]
Poracle generates an error if static map doesn't generate. New logging PR in debug mode will show URL generated which will allow you to see if there are problems in the future (already put it in to help track down any issues!)

**Comment by kamieniarz** [comment]
I'm still having this issue 😫 And I think it's not about generating, cause some messages have staticmap, some not. Is there any way to determine what's wrong?
