### ISSUE TITLE
Giving role from `userRole` doesn't always grant access to Poracle

### ISSUE THREAD

**Issue by kamieniarz** [KartulUdus/PoracleJS#311]
## Expected Behavior
Giving to user any role that's listed in `userRole` should give to user access to Poracle (by adding it to database) and send a welcome message to him.

## Current Behavior
Sometimes Poracle does nothing when new user gets his role so he gets no welcome message and to use Poracle he needs to type `!poracle` in dedicated channel. I've noticed that it happens to ~10-20% of all users I have and mostly to same users - eg. if I give access to user X he needs to register manually, when he loses his role and I give him role back (even a different role from `userRole`) he needs to register too. It looks like it's somehow connected to specific users but the weird thing is they're not any different than other users - they don't have special chars in name or whatever could be the reason for that. Sometimes it's also random so the access won't be granted automatically to an user who never had thati ssue before. I have that issue since I remember so it's for like a year or sth I guess

## Possible Solution
Not so long ago `checkRole` was added - why not do the same but in the opposite way? A simple feature that would check if user with `userRole` is in database so Poracle could add him properly and send him welcome message etc etc

**Comment by jfberry** [comment]
Transferred to wishlist-voting
