### ISSUE TITLE
template names with _ not correctly parsed

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#313]
Hey.

It seems that template names with an _ are no correctly parsed (at least not from TG) and instead just the portion before the _ gets set in the DB.

Also, the bot replies with an OK for unknown names.

Cheers.

**Comment by jfberry** [comment]
Is this with develop or multilang pr?

**Comment by jfberry** [comment]
Reproduced. Not easy to fix because of the way _ is substituted for a space much earlier in the command processing change. Can't see any easy workaround

**Comment by philcerf** [comment]
> Is this with develop or multilang pr?
that was on `develop`

> Not easy to fix because of the way _ is substituted for a space much earlier in the command processing change. Can't see any easy workaround

Well that's what I tried to tell in the other thread, what is problematic about the current way this mapping is done.
Guess the only way is change the template name in the JSON to use spaces rather than _?

At least we have quite a number of commands that give an OK even though they actually failed.
This is one occasion, I think. Probably a check is needed, whether the template name actually exists.

**Comment by jfberry** [comment]
Of course you can't tell whether the template will still exist, or whether your platform language combination exists.
There are more improvements to the parser needed, have tried in multilang to change the hard coded command matching. Ideally there needs to be different rules for different types of parameters, and quoting etc to work. But that is a bigger re-write moving away from regular expressions.

Will get there eventually, but happy to receive pull requests in the meantime if you want to take it on

**Comment by jfberry** [comment]
See #315

**Comment by philcerf** [comment]
Replacing _ with " " in the JSON doesn't work btw..

And just for the records,... I've also noted that the template name in the JSON must be all lower case, otherwise it's never matched-

**Comment by calestyo** [comment]
btw: what still doesn't work: the names seem to be case-sensitive

**Comment by jfberry** [comment]
Please take forward in #317
