### ISSUE TITLE
Use Telegram builtin location function to set location

### ISSUE THREAD

**Issue by hamster007Github** [KartulUdus/PoracleJS#314]
This is a new feature request. Telegram provide a option for users to share there current location. See https://www.guidingtech.com/share-live-location-telegram-android/ chapter "SHARING LIVE LOCATION ON TELEGRAM" for some screenshot, how to share location in Telegram. Only available on mobile Apps I think.
This feature can theoretically used to set user location instead of using location command.

## Expected Behavior
1. User share location in private chat with bot
2. Bot use the received location to set new user location

**Comment by jfberry** [comment]
Like this. I guess the question is whether a live location is just always taken as a location set. If the bot replies to say where the location is set to, I guess it will be obviously what has happened

**Comment by hamster007Github** [comment]
Possible hints from telegram API documentation: 
- message: https://core.telegram.org/bots/api#message -> field "location"
- Location type: https://core.telegram.org/bots/api#location

**Comment by hamster007Github** [comment]
Implemented in #359
