### ISSUE TITLE
allow to forbid individually tracking everything

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#319]
Hey.

As far as I can see:
```
        "disableEverythingTracking": false,
        "forceEverythingSeparately": false,
```
allow to forbid `everything` altogether (via `disableEverythingTracking`), or make `everything` always resolve into individual rules (via `forceEverythingSeparately`).

IMO, the really interesting option would however be the opposite of  `forceEverythingSeparately`, i.e. an option that allows denying people to use `individually` with the command and force them to use the "real" everything (i.e. pokemon_id=0) or at least manually enter rule by rule.

Cheers!

**Comment by jfberry** [comment]
Feels like whoever takes this on should consider a config change
everythingBehaviour: 
to one of 
"normal"
"disable"
"alwaysIndividually"
"disallowIndividually"

We could detect the combinations of the old verbs in the new config checker (log PR) if the new behaviour isn't present in local.json 

Will help anyone who wants to take a crack at this

**Comment by jfberry** [comment]
If someone wants to do this see also #299 which could be handled at the same time (no need to be optional)

**Comment by philcerf** [comment]
Guess we can close this issue, since the my PR #326 is already in the queue.
