### ISSUE TITLE
need contextual help with translations

### ISSUE THREAD

**Issue by calestyo** [KartulUdus/PoracleJS#320]
Hey.

Based on `PoracleJS/config/locale/fr.json` I've started with the German translation, which, as of now is in the following state:

My problem is, that for many strings the context is pretty much unclear (even when looking for it in the sources).
Especially:

1) Are the following all (only) parts of commands respectively their parameters (i.e. **not** a command’s output)?
- `add`
- `remove`
- `level`
- `template`
- `d`
- `female`
- `male`
- `genderless`
- `gen`
- `everything`
- `individually`
- `maxlevel`
- `great`
- `greatcp`
- `ultra`
- `ultracp`
- `maxcp`
- `maxiv`
- `maxweight`
- `maxatk`
- `maxdef`
- `maxsta`
- `cp`
- `iv`
- `atk`
- `def`
- `sta`
- `weight`
- `language`
- `area`
- `egg`
- `help`
- `invasion`
- `location`
- `poracle`
- `quest`
- `raid`
- `start`
- `stop`
- `track`
- `tracked`
- `unregister`
- `untrack`
- `weather`
- `list`
- `instinct`
- `valor`
- `mystic`

At least this:
- `form`
seems to be used in both command and text-output context, in which case I would write once "form" and once "Form" in German.

2. I assume these is all just the weather forms:
- `sunny`
- `rain`
- `partly cloudy`
- `cloudy`
- `windy`
- `snow`
- `fog`

But isn't there a different name for `sunny`, depending on whether it's day or night?

3. I assume these are all used for quests:
 - `Poke Ball`
- `Great Ball`
- `Ultra Ball`
- `Potion`
- `Super Potion`
- `Hyper Potion`
- `Max Potion`
- `Revive`
- `Max Revive`
- `Incense Ordinary`
- `Normal Lure Module`
- `Glacial Lure Module`
- `Mossy Lure Module`
- `Magnetic Lure Module`
- `Razz Berry`
- `Nanab Berry`
- `Pinap Berry`
- `Golden Razz Berry`
- `Silver Pinap Berry`
- `Poffin`
- `Sun Stone`
- `Kings Rock`
- `Metal Coat`
- `Dragon Scale`
- `Up Grade`
- `Gen4 evolution stone`
- `Gen5 evolution stone`
- `Fast TM`
- `Charged TM`
- `Rare Candy`

But are they used solely for output or also for any commands?

4. For they invasion types, there seem to be no translations for:
Mixed, Arlo, Cliff, Sierra, Decoy, Giovanni

5. What about these... commands/parameters... or just output?
- `english`
- `french`
- `spanish`
- `italian`
- `german`
- `japanese`
- `korean`
- `polish`
- `russian`
- `webhook`
- `nameYourWebhookName`
- `name`
- `add`
- `channel`
- `distance`
- `raids`
- `eggs`
- `reward`
- `energy`
- `stardust`
- `Stardust`

and especially these:
- `clean`
- `all items`
- `all pokemon`
- `Everything`
- `any`
- `greatpvp`
- `ultrapvp`
- `gender`
- `unknown`

6. Last but not least, I assume these are all form names for commands?
- `Autumn`
- `Blue Striped`
- `East Sea`
- `Fall 2019`
- `Galarian`
- `Mega`
- `Mega X`
- `Mega Y`
- `Overcast`
- `Plant`
- `Rainy`
- `Red Striped`
- `Sandy`
- `Snowy`
- `Spring`
- `Summer`
- `Sunny`
- `Trash`
- `West Sea`
- `Winter`
- `Adventure Hat 2020`
- `Winter 2020`

I especially ask, because:
- in commands one wouldn't necessarily translate everything in German, because it might just sound stupid ... also one would use lower case (because of the command), whereas the German word would often start with upper case.
- WRT form names/commands... are they case-sensitive? Cause that would probably change how I translate some things... also template names seem to be case sensitive (see #313)

btw: some of the above strings (i.e. the English ones) seem to be missing from the sources... so maybe some of them is legacy cruft.

Thanks.

**Comment by calestyo** [comment]
Well for whichever reason, crappy github didn't let me upload the JSON (changing the extension didn't help either):

```
{
	"Oops, both Great and Ultra league parameters were set in command! - check the":"Ups, sowohl Super- als auch Hyperliga Parameter wurden im Befehl gesetzt. Konsultieren Sie die",
	"Oops, a distance was set in command but no location is defined for your tracking - check the":"Ups, im Befehl wurde eine Distanz gesetzt aber es ist kein Standort festgelegt. Konsultieren Sie die",
	"Oops, no distance was set in command and no area is defined for your tracking - check the":"Ups, im Befehl wurde keine Distanz gesetzt aber es ist kein Gebiet festgelegt. Konsultieren Sie die",
	"Please run commands in Direct Messages":"Bitte sende Befehle als Direktnachrichten!",
	"Current language is set to":"Momentan ist Ihre Sprache wie folgt gesetzt:",
	"I only recognise the following languages":"Es werden nur die folgenden Sprachen erkannt:",
	"I have changed your language setting to":"Ihre Sprache wurde wie folgt gesetzt:",
	"You have reached the limit of":"Sie haben das Limit von",
	"messages over":"Nachrichten über",
	"seconds":"Sekunden erreicht.",
	"english":"Englisch",
	"french":"Französisch",
	"spanish":"Spanisch",
	"italian":"Italienisch",
	"german":"Deutsch",
	"japanese":"Japanisch",
	"korean":"Koreanisch",
	"polish":"Polnisch",
	"russian":"Russisch",
	"name":"",
	"does not seem to be registered. add it with":"scheint nicht registriert zu sein. Füge Sie ihn hinzu mit",
	"webhook":"",
	"add":"",
	"<Your-Webhook-url>":"<Ihr-Webhook-URL>",
	"channel":"",
	"no valid areas there, please use one of":"Keine validen Gebiete, bitte verwenden Sie eines aus:",
	"Added areas:":"Hinzgefügte Gebiete:",
	"Removed areas:":"Entfernte Gebiete",
	"Current configured areas are:":"Momentan sind folgende Gebiete gesetzt:",
	"nameYourWebhookName":"",
	"remove":"",
	"level":"",
	"distance":"",
	"raids":"",
	"controlled by":"",
	"must be an EX Gym":"",
	"eggs":"",
	"reward":"",
	"mega energy":"Mega-Energie",
	"Mega Energy":"Mega-Energie",
	"energy":"Energie",
	"or more stardust":"oder mehr Sternenstaub",
	"template":"vorlage",
	"d":"d",
	"404 No raid egg levels found":"404 Keine Raid-Ei Level gefunden",
	"female":"weiblich",
	"male":"männlich",
	"genderless":"geschlechtunbekannt",
	"clean":"",
	"404 No valid invasion types found":"404 Keine validen Team-GO-Rocket-Invasions-Typen gefunden",
	"New location":"Neuer Standort",
	"I set ":"Die Standort von",
	"s location to : ":"wurde auf die folgenden Koordinaten gesetzt:",
	"'s location to the following coordinates in":"wurde auf die folgenden Koordinaten gesetzt:",
	"Oops, you need to specify more than just a city name to locate accurately your position":"Ups, Sie müssen mehr als nur eine Stadt angeben um den Standort eindeutig festzulegen.",
	"gen":"gen",
	"all items":"",
	"all pokemon":"",
	"stardust":"Sternenstaub",
	"Stardust":"Sternenstaub",
	"404 No valid quests found":"404 Keine validen Quests gefunden",
	"form":"",
	"404 no valid tracks found":"",
	"everything":"alle",
	"individually":"individuell",
	"maxlevel":"maxlevel",
	"great":"super",
	"greatcp":"superwp",
	"ultra":"hyper",
	"ultracp":"hyperwp",
	"maxcp":"maxwp",
	"maxiv":"maxiv",
	"maxweight":"maxgewicht",
	"maxatk":"maxatk",
	"maxdef":"maxdef",
	"maxsta":"maxsta",
	"cp":"wp",
	"iv":"iv",
	"atk":"atk",
	"def":"def",
	"sta":"sta",
	"weight":"gewicht",
	"404 No monsters found":"404 Keine Pokémon gefunden",
	"Your location is currently set to":"Ihr Standort ist aktuell wie folgt gesetzt:",
	"You have not set a location yet":"Sie haben noch keinen Standort gesetzt.",
	"Your alerts are currently":"Ihre Benachrichtigungen sind aktuell",
	"enabled":"aktiviert.",
	"disabled":"deaktiviert.",
	"You are currently set to receive alarms in":"Sie bekommen aktuell Benachrichtigungen in",
	"You have not selected any area yet":"Sie haben noch kein Gebiet ausgewählt.",
	"You're tracking the following monsters:":"Sie beobachten die folgenden Pokémon:",
	"You're not tracking any monsters":"Sie beobachten keine Pokémon.",
	"Everything":"",
	"any":"",
	"greatpvp":"superpvp",
	"ultrapvp":"hyperpvp",
	"gender":"",
	"grunt type":"Rüpel-Typ",
	"You're tracking the following raids:":"Sie beobachten die folgenden Raids:",
	"You're not tracking any raids":"Sie beobachten keine Raids.",
	"You're tracking the following quests:":"Sie beobachten die folgenden Quests:",
	"You're not tracking any quests":"Sie beobachten keine Quests.",
	"You're tracking the following invasions:":"Sie beobachten die folgenden Team-GO-Rocket-Invasionen:",
	"You're not tracking any invasions":"Sie beobachten keine Team-GO-Rocket-Invasionen.",
	"Tracking list is quite long. Have a look at":"",
	"Tracking list is long, but Hastebin is also down. ☹️ \nTracking list made into a file:":"",
	"404 no locations found: ":"404 Keine Standorte gefunden",
	"Possible weather change at":"Möglicher Wetterwechsel um",
	"unknown":"unbekannt",
	"language":"sprache",
	"area":"gebiet",
	"egg":"ei",
	"help":"hilfe",
	"invasion":"invasion",
	"location":"standort",
	"poracle":"poracle",
	"quest":"quest",
	"raid":"raid",
	"start":"start",
	"stop":"stop",
	"track":"",
	"tracked":"",
	"unregister":"",
	"untrack":"",
	"weather":"wetter",
	"list":"",
	"instinct":"Intuition",
	"valor":"Wagemut",
	"mystic":"Weisheit",
	"sunny":"Sonnig",
	"rain":"Regen",
	"partly cloudy":"Teilweise bewölkt",
	"cloudy":"Bedeckt",
	"windy":"Windig",
	"snow":"Schnee",
	"fog":"Nebel",
	"Poke Ball":"Pokéball",
	"Great Ball":"Superball",
	"Ultra Ball":"Hyperball",
	"Potion":"Trank",
	"Super Potion":"Supertrank",
	"Hyper Potion":"Hypertrank",
	"Max Potion":"Top-Trank",
	"Revive":"Beleber",
	"Max Revive":"Top-Beleber",
	"Incense Ordinary":"Rauch",
	"Normal Lure Module":"Lockmodul",
	"Glacial Lure Module":"Gletscher-Lockmodul",
	"Mossy Lure Module":"Moos-Lockmodul",
	"Magnetic Lure Module":"Magnet-Lockmodul",
	"Razz Berry":"Himmihbeere",
	"Nanab Berry":"Nanabbeere",
	"Pinap Berry":"Sananabeere",
	"Golden Razz Berry":"Goldene Himmihbeere",
	"Silver Pinap Berry":"Silberne Sananabeere",
	"Poffin":"Knursp",
	"Sun Stone":"Sonnenstein",
	"Kings Rock":"King-Stein",
	"Metal Coat":"Metallmantel",
	"Dragon Scale":"Drachenhaut",
	"Up Grade":"Up-Grade",
	"Gen4 evolution stone":"Sinnoh-Stein",
	"Gen5 evolution stone":"Einall-Stein",
	"Fast TM":"Sofort-TM",
	"Charged TM":"Lade-TM",
	"Rare Candy":"Sonderbonbon",
	"Bug":"Käfer",
	"Dark":"Unlicht",
	"Dragon":"Drache",
	"Electric":"Elektro",
	"Fairy":"Fee",
	"Fighting":"Kampf",
	"Fire":"Feuer",
	"Flying":"Flug",
	"Ghost":"Geist",
	"Grass":"Pflanze",
	"Ground":"Boden",
	"Ice":"Eis",
	"Normal":"Normal",
	"Poison":"Gift",
	"Psychic":"Psycho",
	"Rock":"Gestein",
	"Steel":"Stahl",
	"Water":"Wasser",
	"Autumn":"Herbstform",
	"Blue Striped":"Blaulinig",
	"East Sea":"Östliches Meer",
	"Fall 2019":"Herbst 2019",
	"Galarian":"Galar",
	"Mega":"Mega",
	"Mega X":"Mega X",
	"Mega Y":"Mega Y",
	"Overcast":"Wolkenform",
	"Plant":"Pflanzenumhang",
	"Rainy":"Regenform",
	"Red Striped":"Rotlinig",
	"Sandy":"Sandumhang",
	"Snowy":"Schneeform",
	"Spring":"Frühlingsform",
	"Summer":"Sommerform",
	"Sunny":"Sonnenform",
	"Trash":"Lumpenumhang",
	"West Sea":"Westliches Meer",
	"Winter":"Winterform",
	"Adventure Hat 2020":"Abenteuer Hut 2020",
	"Winter 2020":"Winter 2020"
}
```

**Comment by jfberry** [comment]
Hi,
Difficult for me to take from that file but send to me over discord or send a pull request in (even better) and I will merge.
The compound translate statements are a bit confusing and your message has reminded me to add a translateFormat function. I've changed the over message limit (ie You have received more than <x> messages in <y> seconds) to use it and updated the french translation.
Other silly compound translations could be moved over to that -- it's quite easy to edit in the code and as long as you update french at the same time everyone will be happy.
Ping me on discord if you'd like to tidy up some of the wierd ones and I'll be happy to point you in the right direction
You are translating some things like 'tracked' to blank, please don't do that - it's a command and I'm not sure we check for that (we reverse translate commands)
If you don't have a translation leave it out
If its the same as english, leave it out

**Comment by philcerf** [comment]
> You are translating some things like 'tracked' to blank, please don't do that - it's a command and I'm not sure we check for that (we reverse translate commands)

Well that's why I didn't sent a PR yet... it's not finished... and I've left the empty ones since I still have to do them.

And it's just because of what I wrote above,... it's not clear to me from fr.json (and also from the code), which of all these strings are commands/parameters of commands, form-names... and which is just plain text...

Isn't that answerable from the groups with comments/questions below, which I've made above?

Or do you have some knowledge about `clean` and `Everything` (with capital E)?

**Comment by philcerf** [comment]
>If you don't have a translation leave it out

that's clear

> If its the same as english, leave it out

for that I'm not so sure whether it's the best approach,... cause one cannot differentiate then, whether the translation hasn't been made yet, or whether it's just identical

**Comment by philcerf** [comment]
Especially these are the most urgent ones:

**What is the context of the following? Commands?**
`name`
`webhook`
`add`
`channel`
`nameYourWebhookName`
`remove`
`level`
`distance`
`raids`
`eggs`
`reward`
`energy`
`clean`
`gen`
`all items`
`all pokemon`
`form`
`list`
`instinct`
`valor`
`mystic`

**What about those?**
`Everything`
`any`
`greatpvp`
`ultrapvp`
`gender`
`unknown`

**Comment by jfberry** [comment]
I do not know the affect of it being present if it translates to the same word.. thinking about it in most cases it would not make any difference (I'm only concerned about the reverse translation though whether it will end up with a double entry)
Many of those are parameters for commands, they are reverse translated as part of the command line parsing.
You should be able to see them being used in the various commands if you grep for them
Note they don't get wrapped in translate commands because they are reversed to english on the way in

Please be aware there is a PR already in for some German translations which I was planning to merge tomorrow

**Comment by philcerf** [comment]
Well I think that for example `level` is used in different contexts... for once it seems to be used as the `levelN` of the commands... but also for some output strings of commands, i.e in the output of `/tracked`.

While digging deeper to find the proper contexts myself I've also noted that several things aren't translated at all.. e.g. "Webhook" doesn't seem to be in some locations.

**Comment by philcerf** [comment]
Oh and thanks for the pointer about the other DE locale PR... I completely missed that, though. ;-D

**Comment by philcerf** [comment]
btw... maybe a longterm idea for translations would be, to also handle English as a locale and use meaningful strings in the code. That would have the advantage that the same (English) word could be translated differently, since the code strings would always be different.

**Comment by philcerf** [comment]
Having English as a locale, too, would also make it easier to keep track of no longer needed/missing strings.


And if one should ever revise this, I'd possibly also suggest to split up the dict in the locale JSON, e.g. like
```
{
"text": {here normal texts}
"commands": {here commands and literal parameters}
"pokemon_name": {...}
"form_names": {...}
}
```

simply to ease translation.

**Comment by jfberry** [comment]
Some re-structuring of the translation file may be nice for the future, and it would be possible to have strings as sources even now though at the expense of making the core code harder to manage, less fragile to english changes.
I was considering this the other day but think we should probably let translation settle a little bit as "much better than it was before" before embarking on further splitting. This may or may not tie up with needing a better command processor.
I would suggest starting a new issue to maintain a list of the things which actually are ambiguous across languages and cause real practical problems so we can capture them all when considering a further round of language based improvements
