### ISSUE TITLE
/quest remove everything doesn't work when disableEverythingTracking=true

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#327]
Hey.

I've noted this during #326, when disableEverythingTracking=true then `/quest remove everything` doesn't work, which makes in principle no sense.

`/untrack everything`, OTOH, does work even then.

Cheers.

**Comment by jfberry** [comment]
Why don't you fix this as part of your PR, it makes sense that it's an everything cleanup

**Comment by philcerf** [comment]
fixed in #326, thus closing here
