### ISSUE TITLE
commands which fail (at least partially) but still show up as having succeeded

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#328]
That issue can be used to track places in Poracle where commands succeed seemingly, though in reality they failed at least partially.

**Comment by philcerf** [comment]
Many commands (e.g. `/area add`|`remove`, `/track`, `/untrack` as well as `/raid`, [/egg](url), `/quest`, `/invasion` and their `… remove` counterparts seem to allow specifying multiple Pokemon/levels/form-names/etc.

However, none of them seems to fail/warn if at least one is valid, e.g.
`/track Bulbasaur RichardFeynman d100`
works just fine.
I think it would genreally be better to fail as soon as just a single token of the input cannot be parsed.

The reason is obvious: end-users may believe that their wrong commands would have worked, while actually they don't get the desired results.

**Comment by philcerf** [comment]
Another example are any commands which are however actually forbidden by the configuration.

Looking at my stuff from PR #326... if `individually` is forbidden by the documentation, the system will simply fall back to using the wildcard-everything,...but the two are obviously different and users will have no chance to notice.
In this example it would probably only lead to annoying support questions, when e.g.
```
/track everything individually great1
/untrack whatTheyAlreadyHave
```
doesn't lead to the expected behaviour.

But when doing e.g. the opposite, (silently) enforcing `individually` they'll now get rules for IDs 1-8xx ... which in 10 years or so may be no longer enough to match future pokemon.
Users would however still thing they track `everything` and potentially miss stuff.

**Comment by philcerf** [comment]
Another example are any commands which use `greatN`, `ultraN`, `greatcpN` or `ultracPN`.
If any values are overridden by the settings in config, the user won't even notice unless he looks up his rules,... which might be pretty unexpected to people... so perhaps giving a warning in these cases would be appropriate.

**Comment by jfberry** [comment]
Given the way that matching works it would be pretty difficult to notice if every argument was used. But perhaps poracle could replay what it has actually understood? After all, it has parsed it and is going to write it to the database.

**Comment by jfberry** [comment]
Agree with this in principle, ... I think the right solution is probably for poracle to output what it is going to do as described above, and plan to implement it this way.  This is now in #wishlist-voting and has a high number of votes and will be implemented so closing here on github to clean up issue lists
