### ISSUE TITLE
Separate response messages for help and start commands

### ISSUE THREAD

**Issue by hamster007Github** [KartulUdus/PoracleJS#351]
On telegram, users get "greeting" template text when typing /help or /start. When users often use /stop and /start, they get every time the long greeting/help text.

Possible solution:
Introduce a new "help" template which is just send on "/help" command. "greeting" text is just send on "/start" command.
Start text can be at example: "You tracking is activated. Type '/help' for more infos about available commands".
Don't know if this behavior fits also for discord.

**Comment by jfberry** [comment]
That sounds like a better idea, will implement
