### ISSUE TITLE
User Location set / area restriction

### ISSUE THREAD

**Issue by lenisko** [KartulUdus/PoracleJS#353]
## Expected Behavior
Add a new options to enable user location set restriction.
With enabled it should allow to set `!location` only within selected areas.

## Current Behavior
`!location` command is ignoring areas. User is able to get alerts for any area within provided distance.

## Possible Solution
For example:

I have 2 areas **Essen** and **Bochum** (both in Germany).

User areas is currently set to nothing `[]`

With an option `restrict_areas_location` enabled, issuing any `!location` will provide an error `Select desired areas first.`

After issuing `!area add Essen` I should be able to set `!location` but only within polygon of Essen area.

So lets say current areas are `['essen']`
Issuing `!location Hovescheidtstraße 25, 45136 Essen, Germany` - should be saved correctly.
But `!location Glockengarten 7, 44803 Bochum, Germany` - should show and error `You can't set location outside of selected areas range.`

As last config option, we could add `restrict_areas_location_match` to instead checking if pokemon is within distance for provided location, we run normal area check AND if it's correct we run additional check to see if it's within location distance.

## Context
This way if user has no `Bochum` in areas he won't get alerts for this area even if his location is within set distance inside `Essen`.
This should also provide enough frame for `role_id<>area` restrictions.

**Comment by kamieniarz** [comment]
Actually I don't see the point of it. Why can't we just let users do whatever they want to? 🤔 

I'd rather say restricting both `area` and `location` to some kind of boundaries (like PMSF does) would be a way better idea than that. Right now if you give access to each city but have only 1 database or rdm/mad instance or juz one poracle instance you can actually track all cities without any limits. Boundaries would help here a lot. I assume that's what you wanted to archieve so you could create an area (that in fact would be some kind of a boundary) but forcing users to set area first and then location just doesn't sound right

**Comment by lenisko** [comment]
It's the correct way to limit boundaries. How would you solve high distance for a location close to "restricted" area close by then? But technically... we could do it in background, so even when user didn't set area we could allow him to set location within it without need to set it first, but that was a plan for second part of changes.

**Comment by kamieniarz** [comment]
We have `userRole` right? We could assing in config each geofence to each role so in fact if you have one big city you'll be limited by its borders. Then user can work with smaller geofences, which are areas actually, and with location limited by the geofence assigned to `userRole`. It's a combination of your first solution and 'doing it in background'. I think that makes sense now

**Comment by lenisko** [comment]
yeah user role would become dictionary where key would be a userId and value list of areas we allow to chose

**Comment by jfberry** [comment]
Transferred to wishlist-voting
