### ISSUE TITLE
Role check crashes if a user leaves the server

### ISSUE THREAD

**Issue by ColdShadow80** [KartulUdus/PoracleJS#357]
info: Service started on 127.0.0.1:4501
info: discord worker #2 Bidoof#7641 ready for action
info: discord worker #1 Bidoof_helper#2626 ready for action
info: discord worker #0 Bidoof_v4#4353 ready for action
info: discord worker #999 Bidoof_v4#4353 ready for action
error: Verification of Poracle user's roles failed with Unknown Member {"name":"DiscordAPIError","method":"get","path":"/guilds/691__**censored_data**___321/members/152__**censored_data**___92","code":10007,"httpStatus":404,"stack":"DiscordAPIError: Unknown Member\n    at RequestHandler.execute (/home/me/progs/PoracleJS/node_modules/discord.js/src/rest/RequestHandler.js:154:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async RequestHandler.push (/home/me/progs/PoracleJS/node_modules/discord.js/src/rest/RequestHandler.js:39:14)\n    at async Worker.checkRole (/home/me/progs/PoracleJS/src/lib/discord/discordWorker.js:174:24)\n    at async Timeout.syncDiscordRole [as _onTimeout] (/home/me/progs/PoracleJS/src/app.js:169:19)"}
info: 17103447325189638000: Boosted Pokémon! Force update of weather in cell 5172347888151298048 with weather 3

## Expected Behavior
Not crashing 😄 
User should be removed from humans table if he leaves the server. Or at least disabled and this should be a info and bypassed as such if possible, continuing role check.

**Comment by jfberry** [comment]
I believe I have fixed this in the performance ++ PR #358 (sorry its wrapped up with a load of other stuff)
