### ISSUE TITLE
Disable notifications when rate limit reached

### ISSUE THREAD

**Issue by kamieniarz** [KartulUdus/PoracleJS#369]
Some users are just the worst and they keep their notifications unchanged, even if they reach rate limit constantly. So the only way to check if someone reached the limit is to check logs which isn't that convenient. The best way would be to have an option to set a number of reached rate limits that would simply disable notifications - maybe sth like `limitReached` under `alertLimits` section. 

So if `limitReached` would be 5 then user that reached rate limit 5 times during the day (or maybe during 1 hour or anything else or just make time period configurable?) would have notifications disabled until he enables them manually.

**Comment by jfberry** [comment]
Implemented in #352
