### ISSUE TITLE
Keep users in database after revoking their access

### ISSUE THREAD

**Issue by kamieniarz** [KartulUdus/PoracleJS#375]
## Current Behavior
When user loses his access role (maybe forgot to pay or whatever) he's automatically removed from database. Since we have profiles and actually poracle is way more complex than it was before, I think it's fair that we could save users in database in case they come back one day.

## Expected Behavior
Keep users in database when they lose access role or they get removed by an admin.
Note: `!unregister` command sent by an user should be treated like now - user should be removed from database so it works like some kind of "reset" if he wants to start over.

## Possible Solution
Don't remove users from database - just use same solution as `!stop` does but with "welcome message" after retrieving access.
Also `!unregister` sent by an user should be treated like now but send by an admin (eg. `!unregister @username`) should be treated like `!stop` so in fact admin can unregister user with role same as with revoking access role

**Comment by jfberry** [comment]
This was already in my mind. We now have the admin disable / enable capability which could be used.  
With !stop, users can enable again with !start - that isn't quite what is needed here.  The only reason I didn't make this an option at the same time as introducing !disable is that I wasn't sure what/whether there should be any automatic re-enable criteria (like getting their role back) - and what it should be
