### ISSUE TITLE
Additional checks

### ISSUE THREAD

**Issue by dkmur** [KartulUdus/PoracleJS#394]
Have been chaning a lot of stuff on dicord channels and was checking database, no clue if below statements ae fully correct, but this is what I ran into:

Channel_delete: when deleting a discord channel this doesn't seem to remove it from Poracle DB. I assume this will result in failures to deliver messages when it still has active trackings or in my case pollution of database as trackings has been stopped.
Suggestion: like rolecheck have a channel check and remove from db?

Channel_rename: Poracle doesn't seem to sync channel names which makes it hard to manage via PoracleWeb as it reads from db. In addition when using i.e. ``!apply %events | track fletchling`` would only update the channels that were originally named %events resulting in a mess.
Suggestion: frequent channel name sync.

User_rename: similar to channel sync, I wanted to beat up some users for being rate limited but they changed discord name making it hard(er) to do some easy beating :P

**Comment by jfberry** [comment]
Channel deletes weren't working for a while; this should now fire (not webhooks, but bot added channels) in recent versions.
I agree that a reconcilliation process should fix this (#279 is this also)
Renames don't get tracked, either for channel or user right now - there is another issue raised for user reconcilliation #274 also from you ;-).

**Comment by dkmur** [comment]
forgotten about 274, this issue can be closed I guess :P

**Comment by jfberry** [comment]
Transferred to wishlist-voting
