### ISSUE TITLE
optionto post stopping of notification to seperate channel

### ISSUE THREAD

**Issue by dkmur** [KartulUdus/PoracleJS#402]
Currently notification ``Stopped alerts (rate-limit exceeded too many times) for target discord:user`` is posted in the same channel as all Poracle commands given by users.

I do not want this channel to be seen by users as also setting of location by others is shown there. Additionally I only look at it myself in case someone is experiencing issues.

The message on exceeding rate limit is getting lost a bit and at least to seen by the users themselves hence I would prefer the option to have it posten to a seperate channel, in my case visible for all users to also create awareness on the limit.

**Comment by jfberry** [comment]
Transferred to wishlist voting
