### ISSUE TITLE
Correct documentation of required version of nodejs

### ISSUE THREAD

**Issue by reedy** [KartulUdus/PoracleJS#487]
Getting the `Error: Cannot find module 'worker_threads'` on master.

Quick search of Discord suggests my version of nodejs is too old. That's fine, but it's not seemingly correctly documented anywhere (wiki/GitHub) what version of nodejs is required, nor does the `npm install`/`npm run init` steps complain that my node version is too old.

https://github.com/KartulUdus/PoracleJS#install says 12 or higher

Ubuntu 20.04 for reference (so nodejs `10.19.0~dfsg-3ubuntu1`).

**Comment by jfberry** [comment]
Node 12 is fine - thats what the page says? And the wiki also tells you how to install node 12 from nodesource I think? (I certainly rememebr writing that)

Ubuntu 20 has v10 - which is really poor this version is massively old.

Poracle used to tell you on execution that your node was too old but unfortunately now we use worker_threads it fails before it can even tell you the version is too old.
