### ISSUE TITLE
Document PR should be to devlop, not master

### ISSUE THREAD

**Issue by reedy** [KartulUdus/PoracleJS#488]
What it says on the tin.

**Comment by jfberry** [comment]
Is that not what it says on wiki?

**Comment by reedy** [comment]
Where?

Doesn't say it on https://muckelba.github.io/poracleWiki/contributing.html

And it really should mention it on https://github.com/KartulUdus/PoracleJS/blob/master/README.md

**Comment by jfberry** [comment]
I have updated the contributing page on the wiki, thanks!
