### ISSUE TITLE
stickerUrl in default.json

### ISSUE THREAD

**Issue by Fabio1988** [KartulUdus/PoracleJS#494]
https://github.com/whitewillem/PogoAssets does not have folder structure like it's mentioned in [default.json](config/default.json)
following error will happen in logs
`Failed to send Telegram sticker https://raw.githubusercontent.com/whitewillem/PogoAssets/resized/icons_large/telegram/pokemon_icon_554_2063.webp`

## Expected Behavior

sticker should be send within DTS in telegram?!

## Current Behavior

error in logs

## Steps to Reproduce (for bugs)

1. use default dts for telegram
2. use stickerUrl from default.json
3. track some pokemon in telegram
4. wait until pokemon message will appear
5. search in logs for error

## Your Environment

* Version used: latest on main accessed today 16:00 CEST
* Environment name and version (e.g. npm 5.6.0, nodejs v7.4.0): with dockerfile
* Operating System Ubuntu

**Comment by jfberry** [comment]
I know it's not a complete repository but it's the best I am aware of which I have permission to include as a default.
There are some privately created repositories - perhaps ask on discord?

Good news may be at hand though, because with the new icon naming format (uicons) some of the main repositories may create a webp equivelant

**Comment by jfberry** [comment]
Since I wrote that a UICONS repository for telegram has become available
The UICONS pull request has that as default now feel free to test it!

**Comment by Fabio1988** [comment]
> I know it's not a complete repository but it's the best I am aware of which I have permission to include as a default.
> There are some privately created repositories - perhaps ask on discord?
> 
> Good news may be at hand though, because with the new icon naming format (uicons) some of the main repositories may create a webp equivelant

But path `resized/icons_large/telegram/` does not exist anymore in that repo 😅

Thx for uicons PR, will have a try.

**Comment by jfberry** [comment]
Resolved in uicons now in master and develop
