### ISSUE TITLE
Develop does not check user roles

### ISSUE THREAD

**Issue by ColdShadow80** [KartulUdus/PoracleJS#60]
Develop branch is not cheching user roles before sending private message to users.
Removing role keeps users full control of Poracle bot.

Tested on latest develop, with 3 different users and 2 independent bots assigned to 2 diferent Discord servers

**Comment by ColdShadow80** [comment]
Updated with test details.
Bot keeps sending messages and accepting commands until kicked out of the server.
User gets bot online and full control of bot as soon as he re enters server, even with no role on server.
No role chech detected.

**Comment by KartulUdus** [comment]
slight oof with incidents, fixed in fb360626c0bd2e1e631cd0e376d250a4c1ab90a0
